"""Designed graphics: the explainer-style layouts and documentary cards.

Studied from two reference styles (2026-09): Ali Abdaal's clean explainers and
Nitish Rajput's documentary storytelling. Every graphic here is drawn with PIL
and cached by its content, like the charts and newspapers, so none of them
needs ComfyUI and all of them work for any channel.

Full-frame cutaways (placed by `placement.place_broll` like any B-roll):

* ``statement_card`` -- a sentence set big in serif on an off-white canvas,
  the words marked ``*like this*`` in the accent colour, with a slot on the
  right where the speaker stays live (`place_layout_speakers`).
* ``canvas_card`` -- a generated picture floated in a rounded, shadowed card
  on the off-white canvas, an optional caption chip on it, and the speaker
  live in the right-hand slot. Generated by ComfyUI as a still, then framed
  here (`frame_canvas_card`).
* ``source_quote`` -- "SOURCE: ..." over a darkened picture (or a dark
  gradient) with the cited sentence and its ``==highlighted==`` phrase.
* ``document`` -- a web article (browser chrome) or a book page, headline and
  body with ``==highlighted==`` phrases under a marker sweep.
* ``timeline`` -- a big figure over a ruler of dates, one date marked.

Overlays on the speaker (placed here, not as cutaways):

* ``pill_labels`` -- two to four rounded labels popping in one by one on the
  side away from the face.
* ``numbered_point`` -- a numbered white bar ("1  Super friendly for
  beginners").
* ``name_title`` -- NAME and a subtitle, clean type, bottom right above the
  captions.

Modifiers:

* ``look`` on any generated still (``broll_image``/``canvas_card``):
  ``bw``, ``noir``, ``sepia``, ``red_duotone``, ``blue_duotone``, ``warm``,
  ``cool`` (`apply_look`).
* The "Generative AI" tag on every generated picture that goes on screen
  (`place_ai_labels`, `settings.ai_label`).
"""

import hashlib
import logging
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

from timeline import clip_ops
from timeline.authoring import clear_generated
from timeline.presets import TEXT_ZONE_MAX_POS_Y
from timeline.schema import SourceFile, Timeline, frame_to_time, time_to_frame

from .models import Asset, Beat
from .newspaper import _font, _serif_font

logger = logging.getLogger("presentation.graphics")

# --- the design system ------------------------------------------------------------------

CANVAS = (244, 241, 234)
INK = (30, 30, 32)
MUTED = (118, 112, 104)
ACCENT = (226, 110, 84)          # coral, the highlight colour of the explainer look
MARKER = (255, 226, 64)          # highlighter yellow for documents and source quotes
WHITE = (255, 255, 255)

LAYOUT_ORIGIN = "layout"
LAYOUT_SPEAKER_TRACK = "V5"
OVERLAY_TRACK = "V6"
OVERLAY_ORIGIN = "overlay_graphic"
NAME_TITLE_TRACK = "TX"
AI_LABEL_TRACK = "TA"
AI_LABEL_ORIGIN = "ai_label"
AI_LABEL_TEXT = "Generative AI"

# Kinds drawn here as full-frame cutaways, and those that keep the speaker live.
DRAWN_CUTAWAY_KINDS = ("statement_card", "source_quote", "document", "timeline")
SPEAKER_LAYOUT_KINDS = ("statement_card", "canvas_card")
OVERLAY_KINDS = ("pill_labels", "numbered_point", "name_title")
LOOKS = ("bw", "noir", "sepia", "red_duotone", "blue_duotone", "warm", "cool")

# The speaker slot, as a fraction of the canvas: a 3:4 portrait window centred
# on the right. The PNG draws its frame; `place_layout_speakers` puts the live
# picture exactly inside it (same geometry, render/effects.py overlay maths).
SLOT_CENTRE = (0.835, 0.5)
SLOT_HEIGHT = 0.40
SLOT_ASPECT = 0.75


def _slot_rect(width: int, height: int) -> Tuple[int, int, int, int]:
    h = int(round(height * SLOT_HEIGHT))
    w = int(round(h * SLOT_ASPECT))
    cx, cy = width * SLOT_CENTRE[0], height * SLOT_CENTRE[1]
    return int(cx - w / 2), int(cy - h / 2), int(cx + w / 2), int(cy + h / 2)


# --- small drawing helpers -----------------------------------------------------------------

def _rgba(size: Tuple[int, int]):
    from PIL import Image
    return Image.new("RGBA", size, (0, 0, 0, 0))


def _shadow(base, box: Tuple[int, int, int, int], radius: int, blur: int = 28,
            offset: int = 14, alpha: int = 70) -> None:
    from PIL import Image, ImageDraw, ImageFilter
    layer = Image.new("RGBA", base.size, (0, 0, 0, 0))
    x0, y0, x1, y1 = box
    ImageDraw.Draw(layer).rounded_rectangle((x0, y0 + offset, x1, y1 + offset), radius,
                                            fill=(0, 0, 0, alpha))
    base.alpha_composite(layer.filter(ImageFilter.GaussianBlur(blur)))


def _speaker_frame(image, width: int, height: int) -> None:
    """The white rounded frame (and its shadow) the live speaker sits in."""
    from PIL import ImageDraw
    x0, y0, x1, y1 = _slot_rect(width, height)
    pad = max(6, height // 110)
    box = (x0 - pad, y0 - pad, x1 + pad, y1 + pad)
    _shadow(image, box, radius=pad * 3)
    ImageDraw.Draw(image).rounded_rectangle(box, pad * 3, fill=WHITE + (255,))


_MARK_RE = re.compile(r"(\*[^*]+\*|==[^=]+==)")


def _tokens(text: str) -> List[Tuple[str, bool]]:
    """Words with a flag for "highlighted": `*word*` or `==phrase==` marks."""
    out: List[Tuple[str, bool]] = []
    for part in _MARK_RE.split(text or ""):
        if not part:
            continue
        marked = (part.startswith("*") and part.endswith("*")) or \
                 (part.startswith("==") and part.endswith("=="))
        body = part.strip("*=") if marked else part
        words = body.split()
        # Punctuation straight after a marked phrase ("*more money*,") belongs
        # to the last word, not to a word of its own with a space before it.
        if words and out and not marked and not body[:1].isspace() and not words[0][:1].isalnum():
            last, last_marked = out.pop()
            out.append((last + words.pop(0), last_marked))
        for word in words:
            out.append((word, marked))
    return out


def plain(text: str) -> str:
    return " ".join(w for w, _ in _tokens(text))


def _layout_words(draw, tokens: List[Tuple[str, bool]], font, max_width: float
                  ) -> List[List[Tuple[str, bool, float]]]:
    space = draw.textlength(" ", font=font)
    lines: List[List[Tuple[str, bool, float]]] = [[]]
    used = 0.0
    for word, marked in tokens:
        w = draw.textlength(word, font=font)
        if lines[-1] and used + space + w > max_width:
            lines.append([])
            used = 0.0
        used += (space if lines[-1] else 0.0) + w
        lines[-1].append((word, marked, w))
    return [line for line in lines if line]


def _fit(draw, tokens, font_fn, max_width: float, max_height: float, start: int,
         minimum: int, spacing: float = 1.22):
    size = start
    while size > minimum:
        font = font_fn(size)
        lines = _layout_words(draw, tokens, font, max_width)
        if len(lines) * size * spacing <= max_height:
            return font, lines, size
        size = int(size * 0.92)
    font = font_fn(minimum)
    return font, _layout_words(draw, tokens, font, max_width), minimum


def _draw_marked_lines(draw, lines, font, size: int, x: float, y: float, colour, marked_colour,
                       marker: Optional[Tuple[int, int, int]] = None, spacing: float = 1.22,
                       align_centre_width: Optional[float] = None) -> float:
    space = draw.textlength(" ", font=font)
    for line in lines:
        line_w = sum(w for _, _, w in line) + space * (len(line) - 1)
        cx = x + (align_centre_width - line_w) / 2 if align_centre_width else x
        for word, marked, w in line:
            if marked and marker is not None:
                pad = size * 0.12
                draw.rectangle((cx - pad, y + size * 0.12, cx + w + pad, y + size * 1.08), fill=marker)
            draw.text((cx, y), word, font=font,
                      fill=marked_colour if marked else colour)
            cx += w + space
        y += size * spacing
    return y


# --- full-frame cards -------------------------------------------------------------------------

def render_statement_card(text: str, width: int, height: int, with_speaker: bool = True):
    from PIL import Image, ImageDraw
    image = Image.new("RGBA", (width, height), CANVAS + (255,))
    if with_speaker:
        _speaker_frame(image, width, height)
    draw = ImageDraw.Draw(image)
    left = width * 0.07
    right = (_slot_rect(width, height)[0] - width * 0.05) if with_speaker else width * 0.93
    font, lines, size = _fit(draw, _tokens(text), lambda s: _serif_font(s, bold=True),
                             right - left, height * 0.72, int(height * 0.1), int(height * 0.04))
    block = len(lines) * size * 1.22
    _draw_marked_lines(draw, lines, font, size, left, (height - block) / 2, INK, ACCENT)
    return image.convert("RGB")


def frame_canvas_card(picture_path: str, width: int, height: int, caption: str = "",
                      with_speaker: bool = True):
    """A generated picture as a floating rounded card on the canvas."""
    from PIL import Image, ImageDraw, ImageOps
    image = Image.new("RGBA", (width, height), CANVAS + (255,))
    if with_speaker:
        _speaker_frame(image, width, height)
    card_w = int(width * (0.68 if with_speaker else 0.82))
    card_h = int(card_w * 9 / 16)
    x0 = int(width * 0.04) if with_speaker else (width - card_w) // 2
    y0 = (height - card_h) // 2
    radius = max(12, height // 45)
    _shadow(image, (x0, y0, x0 + card_w, y0 + card_h), radius)
    picture = ImageOps.fit(Image.open(picture_path).convert("RGB"), (card_w, card_h),
                           Image.LANCZOS)
    mask = Image.new("L", (card_w, card_h), 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, card_w, card_h), radius, fill=255)
    image.paste(picture, (x0, y0), mask)
    if caption:
        draw = ImageDraw.Draw(image)
        size = int(height * 0.036)
        font = _serif_font(size, bold=True)
        tx, ty = x0 + card_w * 0.04, y0 + card_h - size * 2.1
        draw.text((tx + 2, ty + 2), caption, font=font, fill=(0, 0, 0, 160))
        draw.text((tx, ty), caption, font=font, fill=WHITE)
    return image.convert("RGB")


def render_source_quote(source: str, quote: str, width: int, height: int,
                        background: Optional[str] = None):
    from PIL import Image, ImageDraw, ImageEnhance, ImageFilter, ImageOps
    if background and Path(background).exists():
        base = ImageOps.fit(Image.open(background).convert("RGB"), (width, height), Image.LANCZOS)
        base = ImageEnhance.Brightness(base.filter(ImageFilter.GaussianBlur(3))).enhance(0.38)
    else:
        base = Image.new("RGB", (width, height), (18, 18, 20))
        glow = Image.new("L", (width, height), 0)
        ImageDraw.Draw(glow).ellipse((-width * 0.2, -height * 0.4, width * 0.8, height * 0.9), fill=60)
        base = Image.composite(Image.new("RGB", (width, height), (70, 40, 30)), base,
                               glow.filter(ImageFilter.GaussianBlur(160)))
    draw = ImageDraw.Draw(base)
    left, top = width * 0.08, height * 0.2
    label = f"SOURCE: {source.upper()}" if source else "SOURCE"
    label_font = _font(int(height * 0.034), bold=True)
    draw.text((left, top), label, font=label_font, fill=MARKER)
    draw.line((left, top + height * 0.055, left + width * 0.18, top + height * 0.055),
              fill=MARKER, width=max(2, height // 360))
    font, lines, size = _fit(draw, _tokens(quote), lambda s: _serif_font(s, bold=True),
                             width * 0.78, height * 0.5, int(height * 0.06), int(height * 0.032))
    _draw_marked_lines(draw, lines, font, size, left, top + height * 0.1, (240, 238, 232), (20, 20, 20),
                       marker=MARKER)
    return base


def render_document(fmt: str, title: str, body: str, width: int, height: int, site: str = ""):
    """`fmt` "web": a browser page; "book": a printed page. Marked phrases get
    the highlighter. The page is drawn tall, then trimmed to its text and
    centred, so a short excerpt is not a sheet of blank paper."""
    from PIL import Image, ImageDraw, ImageFilter
    paper = WHITE if fmt == "web" else (240, 230, 208)
    page_w, max_h = int(width * 0.74), int(height * 0.86)
    page = Image.new("RGB", (page_w, max_h), paper)
    used = _draw_document_page(page, fmt, title, body, width, height, site)
    page = page.crop((0, 0, page_w, min(max_h, max(int(height * 0.42), used))))
    image = Image.new("RGB", (width, height), (38, 38, 42) if fmt == "web" else (58, 50, 42))
    x0, y0 = (width - page.width) // 2, (height - page.height) // 2
    shadow = Image.new("L", (width, height), 0)
    ImageDraw.Draw(shadow).rectangle((x0 + 10, y0 + 18, x0 + page.width + 10, y0 + page.height + 18),
                                     fill=150)
    image.paste((0, 0, 0), (0, 0), shadow.filter(ImageFilter.GaussianBlur(24)))
    image.paste(page, (x0, y0))
    return image


def _draw_document_page(image, fmt: str, title: str, body: str, width: int, height: int,
                        site: str) -> int:
    """Draw onto a page-sized image; returns how far down the text reached."""
    from PIL import ImageDraw
    draw = ImageDraw.Draw(image)
    page_w, page_h = image.size
    x0 = y0 = 0
    pad = page_w * 0.06
    y = y0 + pad * 0.6
    if fmt == "web":
        bar = int(height * 0.05)
        draw.rectangle((x0, y0, x0 + page_w, y0 + bar), fill=(232, 232, 236))
        for i, colour in enumerate(((236, 95, 86), (245, 190, 60), (98, 196, 86))):
            r = bar * 0.16
            cx = x0 + bar * 0.5 + i * bar * 0.45
            draw.ellipse((cx - r, y0 + bar / 2 - r, cx + r, y0 + bar / 2 + r), fill=colour)
        url_font = _font(int(bar * 0.38), bold=False)
        draw.rounded_rectangle((x0 + bar * 2, y0 + bar * 0.2, x0 + page_w - bar, y0 + bar * 0.8),
                               bar * 0.3, fill=WHITE)
        draw.text((x0 + bar * 2.3, y0 + bar * 0.3), site or "www.example.com", font=url_font,
                  fill=MUTED)
        y = y0 + bar + pad * 0.6
    else:
        head_font = _serif_font(int(height * 0.03), bold=True)
        draw.text((x0 + pad, y), f"Book Source: {site}" if site else "Book Source", font=head_font,
                  fill=(90, 70, 50))
        y += height * 0.06
    title_font, title_lines, title_size = _fit(
        draw, _tokens(title), lambda s: _serif_font(s, bold=True), page_w - 2 * pad,
        page_h * 0.28, int(height * 0.06), int(height * 0.03))
    y = _draw_marked_lines(draw, title_lines, title_font, title_size, x0 + pad, y, INK, INK,
                           marker=MARKER)
    y += height * 0.02
    body_font, body_lines, body_size = _fit(
        draw, _tokens(body), lambda s: _serif_font(s, bold=False), page_w - 2 * pad,
        y0 + page_h - pad - y, int(height * 0.042), int(height * 0.022), spacing=1.45)
    y = _draw_marked_lines(draw, body_lines, body_font, body_size, x0 + pad, y, (60, 58, 56),
                           (20, 20, 20), marker=MARKER, spacing=1.45)
    return int(y + pad * 0.8)


def render_timeline(ticks: Sequence[str], active: int, headline: str, caption: str,
                    width: int, height: int):
    from PIL import Image, ImageDraw
    image = Image.new("RGB", (width, height), (16, 18, 20))
    draw = ImageDraw.Draw(image)
    if headline:
        font, lines, size = _fit(draw, _tokens(headline), lambda s: _font(s, bold=True),
                                 width * 0.8, height * 0.34, int(height * 0.2), int(height * 0.08))
        block = len(lines) * size * 1.1
        _draw_marked_lines(draw, lines, font, size, 0, height * 0.36 - block / 2, (126, 232, 120),
                           MARKER, spacing=1.1, align_centre_width=width)
    if caption:
        cap_font = _font(int(height * 0.034), bold=False)
        cap_w = draw.textlength(caption, font=cap_font)
        draw.text(((width - cap_w) / 2, height * 0.56), caption, font=cap_font, fill=(200, 200, 200))
    ruler_y = height * 0.7
    left, right = width * 0.1, width * 0.9
    draw.line((left, ruler_y, right, ruler_y), fill=(210, 210, 210), width=max(2, height // 400))
    count = max(1, len(ticks))
    tick_font = _font(int(height * 0.03), bold=True)
    for i, label in enumerate(ticks):
        x = left + (right - left) * (i / (count - 1) if count > 1 else 0.5)
        on = i == active
        draw.line((x, ruler_y - height * 0.025, x, ruler_y + height * 0.025),
                  fill=ACCENT if on else (210, 210, 210), width=max(2, height // 300))
        tw = draw.textlength(label, font=tick_font)
        draw.text((x - tw / 2, ruler_y + height * 0.035), label, font=tick_font,
                  fill=ACCENT if on else (190, 190, 190))
        if on:
            r = height * 0.014
            draw.ellipse((x - r, ruler_y - r, x + r, ruler_y + r), fill=ACCENT)
    return image


# --- overlays ---------------------------------------------------------------------------------

def render_pill(text: str, height: int, accent: bool = False):
    from PIL import ImageDraw
    size = int(height * 0.04)
    font = _serif_font(size, bold=True)
    probe = ImageDraw.Draw(_rgba((10, 10)))
    tw = probe.textlength(text, font=font)
    pad_x, pad_y = size * 0.75, size * 0.45
    w, h = int(tw + 2 * pad_x), int(size + 2 * pad_y)
    margin = int(size * 0.8)
    image = _rgba((w + 2 * margin, h + 2 * margin))
    _shadow(image, (margin, margin, margin + w, margin + h), radius=h // 2, blur=10, offset=4, alpha=60)
    draw = ImageDraw.Draw(image)
    draw.rounded_rectangle((margin, margin, margin + w, margin + h), h // 2,
                           fill=(ACCENT if accent else WHITE) + (255,))
    draw.text((margin + pad_x, margin + pad_y - size * 0.1), text, font=font,
              fill=WHITE if accent else INK)
    return image


def render_numbered_point(number: str, text: str, height: int):
    from PIL import ImageDraw
    size = int(height * 0.044)
    probe = ImageDraw.Draw(_rgba((10, 10)))
    max_text_w = height * 0.95
    font, lines, size = _fit(probe, _tokens(text), lambda s: _serif_font(s, bold=True),
                             max_text_w, size * 1.25 * 2, size, int(height * 0.028), spacing=1.25)
    lines = lines[:2]
    space = probe.textlength(" ", font=font)
    tw = max(sum(w for _, _, w in line) + space * (len(line) - 1) for line in lines)
    circle = int(height * 0.042 * 1.7)
    pad = int(height * 0.042 * 0.6)
    text_h = size * 1.25 * len(lines)
    w, h = int(pad * 3 + circle + tw), int(max(circle, text_h) + pad * 1.4)
    margin = int(size * 0.8)
    image = _rgba((w + 2 * margin, h + 2 * margin))
    _shadow(image, (margin, margin, margin + w, margin + h), radius=h // 4, blur=14, offset=6, alpha=60)
    draw = ImageDraw.Draw(image)
    draw.rounded_rectangle((margin, margin, margin + w, margin + h), h // 4, fill=WHITE + (255,))
    cx0, cy0 = margin + pad, margin + (h - circle) // 2
    draw.ellipse((cx0, cy0, cx0 + circle, cy0 + circle), fill=ACCENT + (255,))
    num_font = _serif_font(int(circle * 0.62), bold=True)
    nw = draw.textlength(number, font=num_font)
    draw.text((cx0 + (circle - nw) / 2, cy0 + circle * 0.12), number, font=num_font, fill=WHITE)
    _draw_marked_lines(draw, lines, font, size, cx0 + circle + pad,
                       margin + (h - text_h) / 2 - size * 0.08, INK, ACCENT, spacing=1.25)
    return image


# --- colour looks -------------------------------------------------------------------------------

def apply_look(path: str, look: str) -> str:
    """A graded copy of a still (`<name>.<look>.png`), or the path unchanged
    for an unknown look or an unreadable file."""
    look = (look or "").strip().lower()
    if look not in LOOKS:
        return path
    source = Path(path)
    target = source.with_name(f"{source.stem}.{look}.png")
    if target.exists():
        return str(target)
    try:
        from PIL import Image, ImageEnhance, ImageOps
        image = Image.open(source).convert("RGB")
        gray = ImageOps.grayscale(image)
        if look == "bw":
            out = ImageEnhance.Contrast(gray).enhance(1.15).convert("RGB")
        elif look == "noir":
            out = ImageOps.autocontrast(ImageEnhance.Contrast(gray).enhance(1.6), cutoff=2).convert("RGB")
        elif look == "sepia":
            out = ImageOps.colorize(gray, black=(30, 18, 8), white=(250, 232, 196), mid=(160, 118, 72))
        elif look == "red_duotone":
            out = ImageOps.colorize(ImageEnhance.Contrast(gray).enhance(1.25),
                                    black=(12, 4, 6), white=(255, 214, 200), mid=(170, 28, 38))
        elif look == "blue_duotone":
            out = ImageOps.colorize(gray, black=(6, 10, 26), white=(214, 234, 255), mid=(40, 90, 170))
        elif look == "warm":
            r, g, b = image.split()
            out = Image.merge("RGB", (r.point(lambda v: min(255, int(v * 1.08 + 6))), g,
                                      b.point(lambda v: int(v * 0.88))))
        else:  # cool
            r, g, b = image.split()
            out = Image.merge("RGB", (r.point(lambda v: int(v * 0.9)), g,
                                      b.point(lambda v: min(255, int(v * 1.08 + 6)))))
        out.save(target)
        return str(target)
    except Exception as e:
        logger.warning("Look %s on %s failed: %s", look, path, e)
        return path


def post_process_generated(assets: List[Asset], beats: Sequence[Beat], width: int,
                           height: int) -> List[Asset]:
    """Looks on generated stills, then canvas framing for `canvas_card`. A clip
    (video) keeps its motion and is left alone."""
    by_id = {b.id: b for b in beats}
    for asset in assets:
        beat = by_id.get(asset.beat_id)
        if beat is None or asset.kind != "image":
            continue
        data = beat.data or {}
        look = data.get("look")
        if look:
            asset.path = apply_look(asset.path, str(look))
        if beat.kind == "canvas_card":
            key = hashlib.sha1(f"{asset.path}|{data.get('caption')}|{width}x{height}|"
                               f"{data.get('with_speaker', True)}".encode()).hexdigest()[:12]
            target = Path(asset.path).with_name(f"canvas_{key}.png")
            if not target.exists():
                try:
                    frame_canvas_card(asset.path, width, height, str(data.get("caption") or ""),
                                      bool(data.get("with_speaker", True))).save(target)
                except Exception as e:
                    logger.warning("Canvas card for %s failed: %s", beat.id, e)
                    continue
            asset.path, asset.width, asset.height = str(target), width, height
    return assets


# --- drawn cutaway assets ---------------------------------------------------------------------

def render_graphic_assets(beats: Sequence[Beat], project_dir: Path, width: int, height: int,
                          generated: Sequence[Asset] = ()) -> Tuple[List[Asset], List[Dict[str, str]]]:
    """PNG cutaways for statement cards, source quotes, documents and timelines."""
    assets: List[Asset] = []
    failures: List[Dict[str, str]] = []
    wanted = [b for b in beats if b.kind in DRAWN_CUTAWAY_KINDS]
    if not wanted:
        return assets, failures
    directory = Path(project_dir) / "assets" / "graphics"
    directory.mkdir(parents=True, exist_ok=True)
    pictures = {a.beat_id: a.path for a in generated if a.kind == "image"}
    for beat in wanted:
        data = dict(beat.data or {})
        key = hashlib.sha1(f"{beat.kind}|{beat.text}|{beat.subtext}|{sorted(data.items())!r}|"
                           f"{width}x{height}".encode()).hexdigest()[:12]
        path = directory / f"{beat.kind}_{key}.png"
        if not path.exists():
            try:
                if beat.kind == "statement_card":
                    image = render_statement_card(beat.text or "", width, height,
                                                  bool(data.get("with_speaker", True)))
                elif beat.kind == "source_quote":
                    image = render_source_quote(str(data.get("source") or ""), beat.text or "",
                                                width, height, pictures.get(beat.id))
                elif beat.kind == "document":
                    image = render_document(str(data.get("format") or "web"), beat.text or "",
                                            beat.subtext or "", width, height,
                                            str(data.get("site") or ""))
                else:
                    ticks = [str(t) for t in (data.get("ticks") or [])] or ["", ""]
                    image = render_timeline(ticks, int(data.get("active", len(ticks) - 1)),
                                            beat.text or "", beat.subtext or "", width, height)
                image.save(path)
            except Exception as e:
                logger.warning("%s for %r failed: %s", beat.kind, beat.topic, e)
                failures.append({"beat_id": beat.id, "reason": f"render failed: {e}"})
                continue
        assets.append(Asset(beat_id=beat.id, kind="image", path=str(path), width=width,
                            height=height, cache_hit=True))
    return assets, failures


# --- the live speaker in a layout's slot --------------------------------------------------

def _speaker_crop(face_x: float, source_w: int, source_h: int) -> Tuple[float, float]:
    """(crop_left, crop_right) giving a 3:4 window centred on the face."""
    keep = min(1.0, source_h * SLOT_ASPECT / max(1, source_w))
    centre = (face_x + 1.0) / 2.0
    left = min(max(0.0, centre - keep / 2), 1.0 - keep)
    return left, max(0.0, 1.0 - keep - left)


def place_layout_speakers(timeline: Timeline, beats: Sequence[Beat],
                          face_anchors: Optional[Dict[str, Tuple[float, float]]] = None) -> int:
    """The speaker, live, inside the slot of every placed statement/canvas card."""
    clear_generated(timeline, LAYOUT_ORIGIN)
    wanted = {b.id for b in beats if b.kind in SPEAKER_LAYOUT_KINDS
              and (b.data or {}).get("with_speaker", True)}
    if not wanted:
        return 0
    face_anchors = face_anchors or {}
    width, height = timeline.width or 1920, timeline.height or 1080
    slot_h = _slot_rect(width, height)[3] - _slot_rect(width, height)[1]
    scale = slot_h / height
    pos_x = SLOT_CENTRE[0] * 2 - 1.0
    pos_y = SLOT_CENTRE[1] * 2 - 1.0
    v1 = sorted((i for i in timeline.items if i.track == "V1" and i.kind == "media" and i.enabled),
                key=lambda i: i.timeline_start_frame)
    count = 0
    for cut in [i for i in timeline.items if i.kind == "media" and i.source_id
                and any(i.source_id.startswith(f"src_broll_{b}_") for b in wanted)]:
        for segment in v1:
            lo = max(cut.timeline_start_frame, segment.timeline_start_frame)
            hi = min(cut.timeline_end_frame, segment.timeline_end_frame)
            if hi - lo <= 2 or not segment.source_id:
                continue
            source = timeline.sources.get(segment.source_id)
            src_w = (source.width if source and source.width else width)
            src_h = (source.height if source and source.height else height)
            face_x = face_anchors.get(segment.id, (0.0, 0.0))[0]
            crop_left, crop_right = _speaker_crop(face_x, src_w, src_h)
            offset = lo - segment.timeline_start_frame
            item = clip_ops.add_media_item(
                timeline, segment.source_id, LAYOUT_SPEAKER_TRACK, lo,
                segment.source_start_frame + offset,
                segment.source_start_frame + offset + (hi - lo), origin=LAYOUT_ORIGIN)
            item.mute = True
            item.label = "layout: speaker"
            clip_ops.set_transform(timeline, item.id, {
                "scale": scale, "pos_x": pos_x, "pos_y": pos_y,
                "crop_left": crop_left, "crop_right": crop_right})
        count += 1
    if count:
        timeline.recalculate_duration()
        timeline.revision += 1
    return count


# --- overlays on the speaker ------------------------------------------------------------------

def _inside_pos_x(side: float, overlay_w: int, width: int, reach: float) -> float:
    """pos_x for an overlay pushed `reach` of the way toward `side`, pulled in
    so the whole overlay stays inside the frame with a margin."""
    margin = width * 0.03
    limit = max(0.0, (width - overlay_w - 2 * margin) / width)
    return side * min(reach, limit)


def _overlaps(start: float, end: float, windows: Sequence[Tuple[float, float]]) -> bool:
    return any(start < e and s < end for s, e in windows)


def _register_png(timeline: Timeline, path: Path, duration_s: float, image) -> str:
    source_id = f"src_overlay_{path.stem}"
    timeline.sources[source_id] = SourceFile(
        id=source_id, path=str(path), duration_seconds=max(1.0, duration_s),
        width=image.width, height=image.height, fps_num=timeline.fps_num,
        fps_den=timeline.fps_den, has_audio=False, kind="image")
    return source_id


def place_overlays(timeline: Timeline, beats: Sequence[Beat], program, project_dir: Path,
                   busy: Sequence[Tuple[float, float]] = (),
                   face_anchors: Optional[Dict[str, Tuple[float, float]]] = None) -> Dict[str, int]:
    """Pill labels, numbered points and name titles, each at its beat's moment,
    on the side away from the speaker's face, never over a full-frame cutaway."""
    clear_generated(timeline, OVERLAY_ORIGIN)
    counts: Dict[str, int] = {}
    wanted = sorted((b for b in beats if b.kind in OVERLAY_KINDS), key=lambda b: b.start_s)
    if not wanted:
        return counts
    face_anchors = face_anchors or {}
    width, height = timeline.width or 1920, timeline.height or 1080
    fps_num, fps_den = timeline.fps_num, timeline.fps_den
    directory = Path(project_dir) / "assets" / "graphics"
    directory.mkdir(parents=True, exist_ok=True)
    taken: List[Tuple[float, float]] = []
    for beat in wanted:
        start = max(0.0, beat.start_s)
        end = min(program.duration_s, max(beat.end_s, start + 2.5))
        if _overlaps(start, end, busy) or _overlaps(start, end, taken):
            continue
        segment = program.segment_at(start)
        face_x = (face_anchors.get(segment.item_id) or (0.0, 0.0))[0] if segment else 0.0
        side = -1.0 if face_x >= 0.0 else 1.0     # away from the face
        data = beat.data or {}
        if beat.kind == "name_title":
            _place_name_title(timeline, beat, start, end)
        elif beat.kind == "pill_labels":
            items = [str(x) for x in (data.get("items") or []) if str(x).strip()][:4]
            if not items:
                continue
            step = min(0.45, (end - start) / (len(items) + 1))
            gap = 0.14
            top = -gap * (len(items) - 1) / 2
            for index, label in enumerate(items):
                image = render_pill(label, height, accent=bool(data.get("accent_first")) and index == 0)
                path = directory / f"pill_{hashlib.sha1(f'{label}|{height}'.encode()).hexdigest()[:10]}.png"
                if not path.exists():
                    image.save(path)
                appear = start + index * step
                source_id = _register_png(timeline, path, end - appear, image)
                item = clip_ops.add_media_item(
                    timeline, source_id, OVERLAY_TRACK, time_to_frame(appear, fps_num, fps_den), 0,
                    max(1, time_to_frame(end - appear, fps_num, fps_den)), origin=OVERLAY_ORIGIN)
                item.label = f"pill: {label[:24]}"
                clip_ops.set_transform(timeline, item.id, {
                    "scale": image.width / width,
                    "pos_x": _inside_pos_x(side, image.width, width, 0.55),
                    "pos_y": top + gap * index * 2})
        else:
            number = str(data.get("number") or "1")
            image = render_numbered_point(number, plain(beat.text or ""), height)
            path = directory / f"point_{hashlib.sha1(f'{number}|{beat.text}|{height}'.encode()).hexdigest()[:10]}.png"
            if not path.exists():
                image.save(path)
            source_id = _register_png(timeline, path, end - start, image)
            item = clip_ops.add_media_item(
                timeline, source_id, OVERLAY_TRACK, time_to_frame(start, fps_num, fps_den), 0,
                max(1, time_to_frame(end - start, fps_num, fps_den)), origin=OVERLAY_ORIGIN)
            item.label = f"point {number}: {(beat.text or '')[:24]}"
            clip_ops.set_transform(timeline, item.id, {
                "scale": image.width / width,
                "pos_x": _inside_pos_x(side, image.width, width, 0.5), "pos_y": -0.62})
        counts[beat.kind] = counts.get(beat.kind, 0) + 1
        taken.append((start, end))
    if counts:
        timeline.recalculate_duration()
        timeline.revision += 1
    return counts


def _place_name_title(timeline: Timeline, beat: Beat, start: float, end: float) -> None:
    fps_num, fps_den = timeline.fps_num, timeline.fps_den
    frames = max(1, time_to_frame(end - start, fps_num, fps_den))
    first = time_to_frame(start, fps_num, fps_den)
    name = clip_ops.add_text_item(
        timeline, (beat.text or "").upper(), first, frames, track=NAME_TITLE_TRACK,
        style={"font_family": "Montserrat", "font_size": 58, "bold": True, "color": "white",
               "stroke_width": 3, "stroke_color": "black@0.6", "align": "right",
               "pos_x": 0.92, "pos_y": TEXT_ZONE_MAX_POS_Y - 0.1,
               "animation": "fade", "animation_duration": 0.3})
    name.origin = OVERLAY_ORIGIN
    name.label = f"name: {beat.text}"
    if beat.subtext:
        sub = clip_ops.add_text_item(
            timeline, beat.subtext.upper(), first, frames, track=NAME_TITLE_TRACK,
            style={"font_family": "Montserrat", "font_size": 30, "bold": False,
                   "color": "#E8E8E8", "stroke_width": 2, "stroke_color": "black@0.6",
                   "align": "right", "pos_x": 0.92, "pos_y": TEXT_ZONE_MAX_POS_Y,
                   "animation": "fade", "animation_duration": 0.3})
        sub.origin = OVERLAY_ORIGIN
        sub.label = f"name sub: {beat.subtext}"


# --- the disclosure tag -----------------------------------------------------------------------

def place_ai_labels(timeline: Timeline, generated_beat_ids: Sequence[str]) -> int:
    """"Generative AI" in the bottom-left corner over every generated picture
    on screen. YouTube expects realistic synthetic imagery to be disclosed;
    the reference documentary tags every one of its AI stills the same way."""
    clear_generated(timeline, AI_LABEL_ORIGIN)
    ids = set(generated_beat_ids)
    if not ids:
        return 0
    count = 0
    for item in [i for i in timeline.items if i.kind == "media" and i.source_id
                 and i.track != "V1" and i.origin in ("broll",)]:
        beat_id = item.source_id[len("src_broll_"):].rsplit("_", 1)[0] \
            if item.source_id.startswith("src_broll_") else None
        if beat_id not in ids:
            continue
        label = clip_ops.add_text_item(
            timeline, AI_LABEL_TEXT, item.timeline_start_frame, item.duration_frames,
            track=AI_LABEL_TRACK,
            style={"font_family": "Inter", "font_size": 22, "bold": False, "color": "white@0.75",
                   "stroke_width": 1, "stroke_color": "black@0.5", "align": "left",
                   "pos_x": -0.96, "pos_y": 0.93, "animation": "none"})
        label.origin = AI_LABEL_ORIGIN
        label.label = "ai label"
        count += 1
    return count
